### ISSUE TITLE
Could use a link to the repository from the docs

### ISSUE THREAD

**Issue by lmorchard** [Raathigesh/retoggle#6]
Just found this project from React Status and clicked through to the debuggable.io site. But, from there, I didn't see any way to get to this github repo. Oblivious me, I missed the link to the repo from the React Status newsletter. So I googled for "github retoggle" to get here. But, a link from the published docs would be nice too!

**Comment by Raathigesh** [comment]
Hey @lmorchard,

I totally missed that. Thank you for pointing it out 👍
