### ISSUE TITLE
Does not work with SSR

### ISSUE THREAD

**Issue by einarlove** [Raathigesh/retoggle#8]
Love the project so I'm sad to find out this does not work for me because it fails for me when building with `gatsby build`
> WebpackError: ReferenceError: window is not defined

but you can easily test it yourself with:

```js
// fail-retoggle.js
require('retoggle')
```
```ssh
node fail-retoggle.js
```

And get
> ReferenceError: window is not defined

I tried searching for references to `window` in this project but could not find any which confuses me. Anyone else bumping into this problem?

**Comment by Raathigesh** [comment]
I was trying to run a non-minified version via node and currently the bundle target is set to `web` in webpack so I tried building by setting the webpack target to `node` and when I run that, there are some other libraries fail to load as they are dependent on window. 

Sorry, I don't have an immediate solution for you yet.

**Comment by ilovedesert001** [comment]
Maybe something like this ?

```

const WithRetoggle = (props) => {
  const [retoggle, setRetoggle] = useState(null)
  useEffect(() => {
    const load = async() => {
      const retoggle = await import('retoggle')
      setRetoggle(retoggle)
    }
    load()
  }, [])

  if (typeof window === 'undefined' || !retoggle) {
    return null
  } else {
    return props.render(retoggle)
  }
}

function ShowState (state) {
  return (
    <WithRetoggle render={(retoggle) => {
      const {Inspector, useLog} = retoggle
      useLog('state', state)
      return (<Inspector/>)
    }}
    />
  )
}


```

**Comment by alampros** [comment]
I've tried getting this to work with [Gatsby](https://www.gatsbyjs.org/) and failed miserably. A little digging shows the problem seems to stem from [react-json-view#121](https://github.com/mac-s-g/react-json-view/issues/121).

**Comment by dhmacs** [comment]
@Raathigesh is there any plan to fix this? I'm trying to play with Next js but it doesn't work

**Comment by Raathigesh** [comment]
@dhmacs I don't have plans to work on it.

**Comment by dhmacs** [comment]
@Raathigesh nice project tho! 👍  I might draw inspiration to build something similar with SSR support

**Comment by Raathigesh** [comment]
If you want to make re-toggle better, I can invite you as a contributor. I"m personally focusing on another project so I'm not having enough time to focus on retoggle.

**Comment by dhmacs** [comment]
@Raathigesh I would like to sketch something on my own before deciding if it makes sense to make a new package or contribute to this one 👍
