### ISSUE TITLE
Get missing keys warning from React

### ISSUE THREAD

**Issue by einarlove** [Raathigesh/retoggle#9]
I get
> Warning: Each child in an array or iterator should have a unique "key" prop.

for each knob added to the inspector. Is this a known issue?

**Comment by vivek12345** [comment]
For this key issue, should we just add the Component.displayName || Component.name as the key?
@Raathigesh

**Comment by Raathigesh** [comment]
@vivek12345 If that works, that ok too 👍

**Comment by hetpatel33** [comment]
Is anyone working on this? I am interested in claiming.

**Comment by vivek12345** [comment]
@hetpatel33 you can claim this.

**Comment by hetpatel33** [comment]
> @hetpatel33 you can claim this.

Okay, I will submit a PR when it's done. Thanks.

**Comment by Raathigesh** [comment]
Fixed and released with https://github.com/Raathigesh/retoggle/releases/tag/v0.2.1

**Comment by gitnix** [comment]
Getting this for `version "0.3.0"`.
<img width="793" alt="key warning" src="https://user-images.githubusercontent.com/5448785/54963086-d2d0a800-4f3d-11e9-9075-6f3556a05230.png">

**Comment by yyynnn** [comment]
still here 0.3.0
